/**
 * Copyright 2017 Moshe Simantov
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* eslint-disable prettier/prettier */

export default {
  'Buffer': Buffer,
  'Buffer.alloc': Buffer.alloc,
  'Buffer.alloc.prototype': Buffer.alloc.prototype,
  'Buffer.allocUnsafe': Buffer.allocUnsafe,
  'Buffer.allocUnsafe.prototype': Buffer.allocUnsafe.prototype,
  'Buffer.allocUnsafeSlow': Buffer.allocUnsafeSlow,
  'Buffer.allocUnsafeSlow.prototype': Buffer.allocUnsafeSlow.prototype,
  'Buffer.byteLength': Buffer.byteLength,
  'Buffer.byteLength.prototype': Buffer.byteLength.prototype,
  'Buffer.compare': Buffer.compare,
  'Buffer.compare.prototype': Buffer.compare.prototype,
  'Buffer.concat': Buffer.concat,
  'Buffer.concat.prototype': Buffer.concat.prototype,
  'Buffer.from': Buffer.from,
  'Buffer.from.prototype': Buffer.from.prototype,
  'Buffer.isBuffer': Buffer.isBuffer,
  'Buffer.isBuffer.prototype': Buffer.isBuffer.prototype,
  'Buffer.isEncoding': Buffer.isEncoding,
  'Buffer.isEncoding.prototype': Buffer.isEncoding.prototype,
  'Buffer.prototype': Buffer.prototype,
  'Buffer.prototype.asciiSlice': Buffer.prototype.asciiSlice,
  'Buffer.prototype.asciiSlice.prototype': Buffer.prototype.asciiSlice.prototype,
  'Buffer.prototype.asciiWrite': Buffer.prototype.asciiWrite,
  'Buffer.prototype.asciiWrite.prototype': Buffer.prototype.asciiWrite.prototype,
  'Buffer.prototype.base64Slice': Buffer.prototype.base64Slice,
  'Buffer.prototype.base64Slice.prototype': Buffer.prototype.base64Slice.prototype,
  'Buffer.prototype.base64Write': Buffer.prototype.base64Write,
  'Buffer.prototype.base64Write.prototype': Buffer.prototype.base64Write.prototype,
  'Buffer.prototype.compare': Buffer.prototype.compare,
  'Buffer.prototype.compare.prototype': Buffer.prototype.compare.prototype,
  'Buffer.prototype.copy': Buffer.prototype.copy,
  'Buffer.prototype.copy.prototype': Buffer.prototype.copy.prototype,
  'Buffer.prototype.equals': Buffer.prototype.equals,
  'Buffer.prototype.equals.prototype': Buffer.prototype.equals.prototype,
  'Buffer.prototype.fill': Buffer.prototype.fill,
  'Buffer.prototype.fill.prototype': Buffer.prototype.fill.prototype,
  'Buffer.prototype.hexSlice': Buffer.prototype.hexSlice,
  'Buffer.prototype.hexSlice.prototype': Buffer.prototype.hexSlice.prototype,
  'Buffer.prototype.hexWrite': Buffer.prototype.hexWrite,
  'Buffer.prototype.hexWrite.prototype': Buffer.prototype.hexWrite.prototype,
  'Buffer.prototype.includes': Buffer.prototype.includes,
  'Buffer.prototype.includes.prototype': Buffer.prototype.includes.prototype,
  'Buffer.prototype.indexOf': Buffer.prototype.indexOf,
  'Buffer.prototype.indexOf.prototype': Buffer.prototype.indexOf.prototype,
  'Buffer.prototype.inspect': Buffer.prototype.inspect,
  'Buffer.prototype.inspect.prototype': Buffer.prototype.inspect.prototype,
  'Buffer.prototype.lastIndexOf': Buffer.prototype.lastIndexOf,
  'Buffer.prototype.lastIndexOf.prototype': Buffer.prototype.lastIndexOf.prototype,
  'Buffer.prototype.latin1Slice': Buffer.prototype.latin1Slice,
  'Buffer.prototype.latin1Slice.prototype': Buffer.prototype.latin1Slice.prototype,
  'Buffer.prototype.latin1Write': Buffer.prototype.latin1Write,
  'Buffer.prototype.latin1Write.prototype': Buffer.prototype.latin1Write.prototype,
  'Buffer.prototype.readDoubleBE': Buffer.prototype.readDoubleBE,
  'Buffer.prototype.readDoubleBE.prototype': Buffer.prototype.readDoubleBE.prototype,
  'Buffer.prototype.readDoubleLE': Buffer.prototype.readDoubleLE,
  'Buffer.prototype.readDoubleLE.prototype': Buffer.prototype.readDoubleLE.prototype,
  'Buffer.prototype.readFloatBE': Buffer.prototype.readFloatBE,
  'Buffer.prototype.readFloatBE.prototype': Buffer.prototype.readFloatBE.prototype,
  'Buffer.prototype.readFloatLE': Buffer.prototype.readFloatLE,
  'Buffer.prototype.readFloatLE.prototype': Buffer.prototype.readFloatLE.prototype,
  'Buffer.prototype.readInt16BE': Buffer.prototype.readInt16BE,
  'Buffer.prototype.readInt16BE.prototype': Buffer.prototype.readInt16BE.prototype,
  'Buffer.prototype.readInt16LE': Buffer.prototype.readInt16LE,
  'Buffer.prototype.readInt16LE.prototype': Buffer.prototype.readInt16LE.prototype,
  'Buffer.prototype.readInt32BE': Buffer.prototype.readInt32BE,
  'Buffer.prototype.readInt32BE.prototype': Buffer.prototype.readInt32BE.prototype,
  'Buffer.prototype.readInt32LE': Buffer.prototype.readInt32LE,
  'Buffer.prototype.readInt32LE.prototype': Buffer.prototype.readInt32LE.prototype,
  'Buffer.prototype.readInt8': Buffer.prototype.readInt8,
  'Buffer.prototype.readInt8.prototype': Buffer.prototype.readInt8.prototype,
  'Buffer.prototype.readIntBE': Buffer.prototype.readIntBE,
  'Buffer.prototype.readIntBE.prototype': Buffer.prototype.readIntBE.prototype,
  'Buffer.prototype.readIntLE': Buffer.prototype.readIntLE,
  'Buffer.prototype.readIntLE.prototype': Buffer.prototype.readIntLE.prototype,
  'Buffer.prototype.readUInt16BE': Buffer.prototype.readUInt16BE,
  'Buffer.prototype.readUInt16BE.prototype': Buffer.prototype.readUInt16BE.prototype,
  'Buffer.prototype.readUInt16LE': Buffer.prototype.readUInt16LE,
  'Buffer.prototype.readUInt16LE.prototype': Buffer.prototype.readUInt16LE.prototype,
  'Buffer.prototype.readUInt32BE': Buffer.prototype.readUInt32BE,
  'Buffer.prototype.readUInt32BE.prototype': Buffer.prototype.readUInt32BE.prototype,
  'Buffer.prototype.readUInt32LE': Buffer.prototype.readUInt32LE,
  'Buffer.prototype.readUInt32LE.prototype': Buffer.prototype.readUInt32LE.prototype,
  'Buffer.prototype.readUInt8': Buffer.prototype.readUInt8,
  'Buffer.prototype.readUInt8.prototype': Buffer.prototype.readUInt8.prototype,
  'Buffer.prototype.readUIntBE': Buffer.prototype.readUIntBE,
  'Buffer.prototype.readUIntBE.prototype': Buffer.prototype.readUIntBE.prototype,
  'Buffer.prototype.readUIntLE': Buffer.prototype.readUIntLE,
  'Buffer.prototype.readUIntLE.prototype': Buffer.prototype.readUIntLE.prototype,
  'Buffer.prototype.slice': Buffer.prototype.slice,
  'Buffer.prototype.slice.prototype': Buffer.prototype.slice.prototype,
  'Buffer.prototype.swap16': Buffer.prototype.swap16,
  'Buffer.prototype.swap16.prototype': Buffer.prototype.swap16.prototype,
  'Buffer.prototype.swap32': Buffer.prototype.swap32,
  'Buffer.prototype.swap32.prototype': Buffer.prototype.swap32.prototype,
  'Buffer.prototype.swap64': Buffer.prototype.swap64,
  'Buffer.prototype.swap64.prototype': Buffer.prototype.swap64.prototype,
  'Buffer.prototype.toJSON': Buffer.prototype.toJSON,
  'Buffer.prototype.toJSON.prototype': Buffer.prototype.toJSON.prototype,
  'Buffer.prototype.toString': Buffer.prototype.toString,
  'Buffer.prototype.toString.prototype': Buffer.prototype.toString.prototype,
  'Buffer.prototype.ucs2Slice': Buffer.prototype.ucs2Slice,
  'Buffer.prototype.ucs2Slice.prototype': Buffer.prototype.ucs2Slice.prototype,
  'Buffer.prototype.ucs2Write': Buffer.prototype.ucs2Write,
  'Buffer.prototype.ucs2Write.prototype': Buffer.prototype.ucs2Write.prototype,
  'Buffer.prototype.utf8Slice': Buffer.prototype.utf8Slice,
  'Buffer.prototype.utf8Slice.prototype': Buffer.prototype.utf8Slice.prototype,
  'Buffer.prototype.utf8Write': Buffer.prototype.utf8Write,
  'Buffer.prototype.utf8Write.prototype': Buffer.prototype.utf8Write.prototype,
  'Buffer.prototype.write': Buffer.prototype.write,
  'Buffer.prototype.write.prototype': Buffer.prototype.write.prototype,
  'Buffer.prototype.writeDoubleBE': Buffer.prototype.writeDoubleBE,
  'Buffer.prototype.writeDoubleBE.prototype': Buffer.prototype.writeDoubleBE.prototype,
  'Buffer.prototype.writeDoubleLE': Buffer.prototype.writeDoubleLE,
  'Buffer.prototype.writeDoubleLE.prototype': Buffer.prototype.writeDoubleLE.prototype,
  'Buffer.prototype.writeFloatBE': Buffer.prototype.writeFloatBE,
  'Buffer.prototype.writeFloatBE.prototype': Buffer.prototype.writeFloatBE.prototype,
  'Buffer.prototype.writeFloatLE': Buffer.prototype.writeFloatLE,
  'Buffer.prototype.writeFloatLE.prototype': Buffer.prototype.writeFloatLE.prototype,
  'Buffer.prototype.writeInt16BE': Buffer.prototype.writeInt16BE,
  'Buffer.prototype.writeInt16BE.prototype': Buffer.prototype.writeInt16BE.prototype,
  'Buffer.prototype.writeInt16LE': Buffer.prototype.writeInt16LE,
  'Buffer.prototype.writeInt16LE.prototype': Buffer.prototype.writeInt16LE.prototype,
  'Buffer.prototype.writeInt32BE': Buffer.prototype.writeInt32BE,
  'Buffer.prototype.writeInt32BE.prototype': Buffer.prototype.writeInt32BE.prototype,
  'Buffer.prototype.writeInt32LE': Buffer.prototype.writeInt32LE,
  'Buffer.prototype.writeInt32LE.prototype': Buffer.prototype.writeInt32LE.prototype,
  'Buffer.prototype.writeInt8': Buffer.prototype.writeInt8,
  'Buffer.prototype.writeInt8.prototype': Buffer.prototype.writeInt8.prototype,
  'Buffer.prototype.writeIntBE': Buffer.prototype.writeIntBE,
  'Buffer.prototype.writeIntBE.prototype': Buffer.prototype.writeIntBE.prototype,
  'Buffer.prototype.writeIntLE': Buffer.prototype.writeIntLE,
  'Buffer.prototype.writeIntLE.prototype': Buffer.prototype.writeIntLE.prototype,
  'Buffer.prototype.writeUInt16BE': Buffer.prototype.writeUInt16BE,
  'Buffer.prototype.writeUInt16BE.prototype': Buffer.prototype.writeUInt16BE.prototype,
  'Buffer.prototype.writeUInt16LE': Buffer.prototype.writeUInt16LE,
  'Buffer.prototype.writeUInt16LE.prototype': Buffer.prototype.writeUInt16LE.prototype,
  'Buffer.prototype.writeUInt32BE': Buffer.prototype.writeUInt32BE,
  'Buffer.prototype.writeUInt32BE.prototype': Buffer.prototype.writeUInt32BE.prototype,
  'Buffer.prototype.writeUInt32LE': Buffer.prototype.writeUInt32LE,
  'Buffer.prototype.writeUInt32LE.prototype': Buffer.prototype.writeUInt32LE.prototype,
  'Buffer.prototype.writeUInt8': Buffer.prototype.writeUInt8,
  'Buffer.prototype.writeUInt8.prototype': Buffer.prototype.writeUInt8.prototype,
  'Buffer.prototype.writeUIntBE': Buffer.prototype.writeUIntBE,
  'Buffer.prototype.writeUIntBE.prototype': Buffer.prototype.writeUIntBE.prototype,
  'Buffer.prototype.writeUIntLE': Buffer.prototype.writeUIntLE,
  'Buffer.prototype.writeUIntLE.prototype': Buffer.prototype.writeUIntLE.prototype,
  'Buffer[Symbol.species]': Buffer[Symbol.species],
};
